### PR TITLE
Rebase table validation on goodtables.io

### LINKED ISSUE #1157: OS Packager: comma separator
Hello!

I've tried to upload some sample data but got the following error:

> Duplicate Header:  The header column "," is duplicated.

As showed in the following screenshot:

data-upload

However, apparently, there is no comma after the column.
dataset

### LINKED ISSUE #1293: Use goodtables.io and updated client for data validation
# Description

# Tasks

- [ ] Replace the current API interaction and UI with those of the latest goodtables.io-compatible code.

### PR DESCRIPTION
**Pull request by roll**
- fixes https://github.com/openspending/openspending/issues/1157
- fixes https://github.com/openspending/openspending/issues/1293

### CODE REVIEW

**Comment by roll** [comment]
@akariv 
@pwalsh 
@vitorbaptista 
It works and passes existent tests but we still experience visual design problem described here - https://github.com/frictionlessdata/goodtables-ui/issues/1

ospkg

So what we could do:
- fix on `goodtables-ui` level because the same problem will be for `ckan-goodtables` integration (a few Sam's hours on it is really save a lot of time I suppose) 
- quick fix on `os-packager` level

**Comment by pwalsh** [comment]
@roll not clear to me why we need @smth because https://github.com/frictionlessdata/goodtables-ui/issues/1 indicates this is an issue with missing SASS, but not that needs someone to fix design. If you just need Sam's input to find the right styles, them just arrange a meeting with him, or a text chat, to get that info.

Am I missing something?

@akariv can you please review and check this.

**Comment by vitorbaptista** [comment]
Any news here?

**Comment by roll** [comment]
@vitorbaptista 
I'm close to get on finisihng it. But only thing left here is UI fix on https://github.com/frictionlessdata/goodtables-ui level (and then bumping the version here). So funclional-wise is pretty ready for testing and review.

**Comment by roll** [comment]
@akariv 
@vitorbaptista 
Now it's fully ready for a review. Report UI is fixed. And goodtables.io now uses specs-v1.

**Comment by roll** [comment]
@akariv 
@vitorbaptista 
ping :smiley:

File: app/front/scripts/services/validation.js [hunk 1]
```diff
@@ -1,47 +1,22 @@
...
 
 var _ = require('lodash');
-var utils = require('../../../services/utils');
+var goodtables = require('goodtables');
 
-var goodTablesUrl = '//goodtables.okfnlabs.org/api/run';
+var goodtablesOptions = {
+  apiUrl: 'https://goodtables.io/api',
+  apiToken: 'D0123458B8E36326C60253FE4A7FF6662CAB0C48',
+  apiSourceId: '9b6b6391-5404-4e7f-bdb8-271c2cb42fbb'
```
Comment (vitorbaptista) [inline app/front/scripts/services/validation.js:9]: I guess this shouldn't be here?

File: app/front/scripts/services/validation.js [hunk 2]
```diff
@@ -1,47 +1,22 @@
...
-              }
-              return results;
-            })
-            .catch(function(error) {
-              validationResult.state = null;
-              Configuration.defaultErrorHandler(error);
-            });
-
-          return validationResult;
+          if (source.blob) source = source.blob;
```
Comment (vitorbaptista) [inline app/front/scripts/services/validation.js:18]: I think it's better to avoid multiple statements in a single line, and specially omitting the curly braces. It isn't dangerous here, but patterns have a tendency to spread. For an interesting story about bugs caused by single-line ifs, see https://medium.com/@jonathanabrams/single-line-if-statements-2565c62ff492.

File: app/front/scripts/services/package.js [hunk 3]
```diff
@@ -81,13 +81,20 @@ angular.module('Application')
...
+              };
+              return ValidationService.validateResource(fileOrUrl)
+                .then(function(report) {
+                  encoding = report.tables[0].encoding;
+                  state.status.state = 'completed';
+                  state.status.report = report;
+                  return fileOrUrl;
+                })
+                .catch(function(error) {
+                  state.status.state = null;
```
Comment (vitorbaptista) [inline app/front/scripts/services/package.js]: Is `state.status` modified by anyone else? If so, should it contain data added/modified by different parts of the codebase? If not, I think it's a good defensive practice to change the entire `state.status`, instead of its internal properties. This also makes the intent of the code clearer, as if you're changing just a single property, it makes me wonder what else is in `state.status`.

**Review by vitorbaptista — CHANGES_REQUESTED** [review]
I have just read the code. Apart from the commited API keys, it's looking good.

File: app/front/scripts/services/validation.js (hunk 2 above)
Comment (vitorbaptista) [reply app/front/scripts/services/validation.js:18]: Nevermind what I said above. Although I personally prefer to always use braces, this is fine :+1:

File: app/front/scripts/services/package.js (hunk 3 above)
Comment (roll) [reply app/front/scripts/services/package.js]: TBH I don't know. I was barely able to understand how it works at all. It seems this `state.status.x` is changing in many places across the codebase. So I've just copied its usage from the former code to make this PR minimal - maximising chances to do not break the whole app.

File: app/front/scripts/services/validation.js (hunk 1 above)
Comment (roll) [reply app/front/scripts/services/validation.js:9]: It's publicly available `goodtables.io` credentials to use with `goodtables-js` in a "guest" mode. If you take a look on a high-level architecture - this code executes only on a client so this configuration can't be hidden anyway or lives in app's `config.js`.

**Comment by roll** [comment]
@vitorbaptista 
Please take a look on comments.

File: app/front/scripts/services/validation.js (hunk 1 above)
Comment (vitorbaptista) [reply app/front/scripts/services/validation.js:9]: @roll Cool, let's go with it for now. I opened an issue on https://github.com/frictionlessdata/goodtables.io/issues/279 for us to discuss this further.

File: app/front/scripts/services/package.js (hunk 3 above)
Comment (vitorbaptista) [reply app/front/scripts/services/package.js]: Yeah, this is very tricky. In an abstract level, I don't understand why we would ever want a `status.state` coming from one place, and a `status.report` coming from another. As we're writing `state.status` ourselves, I think we're safe to overwrite it completely here, even if this pattern isn't followed in other parts of the code. At least this start moving us towards safer coding patterns.

File: app/front/scripts/services/upload-file.js [hunk 4]
```diff
@@ -35,7 +35,7 @@ angular.module('Application')
               status.sampleSize += 1;
             }
 
-            if (!status.errors) {
+            if (status.report.valid) {
```
Comment (vitorbaptista) [inline app/front/scripts/services/upload-file.js]: From what I understood, this will fail if there was an error getting the report, as `status.report` will be `undefined`, and `status.report.valid` will raise an exception. We need to check for `status.state === 'completed'`, like you do in the templates. Better yet, we can simply test for `status.report` being defined, this way the dependency between the codebases are simply on `status.report`, and not `status.state`.

**Review by vitorbaptista — APPROVED** [review]
Apart from a couple small tweaks (check comments), all good. As the tweaks are minimal, I took the liberty of doing them myself to avoid breaking your flow. Please take a look on https://github.com/openspending/os-packager/pull/116/commits/22c4f7a0cd226413bc3c95cc7b3a8d06949bd099 and https://github.com/openspending/os-packager/pull/116/commits/123e0eb47a910af34c0ec3c35ddc4dfabf41b989. If you're happy with them, we can (finally) merge this in :+1:

**Comment by roll** [comment]
@vitorbaptista 
Great. Thanks! Please merge.

**Comment by roll** [comment]
@brew 
I've added also you to reviewers if now you're responsible of merging PRs for `os-packager`.
